import Image from "next/image"
import { notFound } from "next/navigation"

import { AccountShell } from "@/components/account/account-shell"
import { CancelBookingButton } from "@/components/account/cancel-booking-button"
import { bookingBalanceCents, formatEuro, humanizeStatus, shortOrderId } from "@/lib/format"
import { requireUser } from "@/lib/supabase/auth"
import { createSupabaseServerClient } from "@/lib/supabase/server"

type DetailRow = { id: string; status: string; payment_status: string; estimated_total_cents: number; confirmed_total_cents: number | null; booking_fee_cents: number; preferred_date: string; preferred_time: string; confirmed_start_at: string | null; contact_name: string; contact_phone: string; address_line_1: string; address_line_2: string | null; city: string; county: string; eircode: string | null; notes: string | null; created_at: string; order_items: Array<{ service_name: string; category: string; quantity: number; unit_estimate_cents: number }>; order_answers: Array<{ question_label: string; answer: string }>; order_photos: Array<{ storage_path: string }> }

export default async function BookingDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  await requireUser(`/account/bookings/${id}`)
  const supabase = await createSupabaseServerClient()
  const { data } = supabase ? await supabase.from("orders").select("id,status,payment_status,estimated_total_cents,confirmed_total_cents,booking_fee_cents,preferred_date,preferred_time,confirmed_start_at,contact_name,contact_phone,address_line_1,address_line_2,city,county,eircode,notes,created_at,order_items(service_name,category,quantity,unit_estimate_cents),order_answers(question_label,answer),order_photos(storage_path)").eq("id", id).maybeSingle() : { data: null }
  if (!data) notFound()
  const booking = data as DetailRow
  const paths = booking.order_photos.map((photo) => photo.storage_path)
  const { data: signed } = paths.length && supabase ? await supabase.storage.from("job-photos").createSignedUrls(paths, 900) : { data: [] }
  const balance = bookingBalanceCents({ status: booking.status, paymentStatus: booking.payment_status, confirmedTotalCents: booking.confirmed_total_cents, estimatedTotalCents: booking.estimated_total_cents, bookingFeeCents: booking.booking_fee_cents })
  const canCancel = ["awaiting_payment", "requested", "confirmed"].includes(booking.status)

  return <AccountShell title={shortOrderId(booking.id)}><div className="grid gap-5 lg:grid-cols-[1.4fr_0.8fr]"><section className="space-y-5 rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold text-[#072d3b]">Booking details</h2><span className="rounded-full bg-[#eef8f6] px-3 py-1 text-sm text-[#0b776a]">{humanizeStatus(booking.status)}</span></div><div className="space-y-3">{booking.order_items.map((item) => <div key={item.service_name} className="flex justify-between border-b pb-3 text-sm"><span>{item.service_name} × {item.quantity}</span><span>{formatEuro(item.unit_estimate_cents * item.quantity)}</span></div>)}</div>{booking.order_answers.length ? <div><h3 className="font-semibold">Information provided</h3><dl className="mt-3 space-y-3 text-sm">{booking.order_answers.map((answer) => <div key={answer.question_label}><dt className="text-slate-400">{answer.question_label}</dt><dd>{answer.answer}</dd></div>)}</dl></div> : null}{signed?.length ? <div><h3 className="font-semibold">Private photos</h3><div className="mt-3 grid grid-cols-3 gap-3">{signed.map((photo, index) => photo.signedUrl ? <div key={photo.signedUrl} className="relative aspect-square overflow-hidden rounded-2xl"><Image src={photo.signedUrl} alt={`Job photo ${index + 1}`} fill sizes="180px" className="object-cover" unoptimized /></div> : null)}</div></div> : null}</section><aside className="space-y-5"><div className="rounded-3xl bg-[#072d3b] p-6 text-white"><p className="text-sm text-white/60">Starting estimate</p><p className="text-2xl font-semibold">{formatEuro(booking.estimated_total_cents)}</p>{booking.confirmed_total_cents !== null ? <><p className="mt-4 text-sm text-white/60">Confirmed total</p><p className="text-2xl font-semibold">{formatEuro(booking.confirmed_total_cents)}</p></> : null}<div className="my-5 border-t border-white/15" /><p>{booking.payment_status === "paid" ? "€10 booking fee paid" : `Payment: ${humanizeStatus(booking.payment_status)}`}</p><p className="mt-2 text-sm text-white/70">Balance collected separately: {formatEuro(balance)}</p></div><div className="rounded-3xl bg-white p-6 text-sm leading-6 shadow-sm"><h3 className="font-semibold text-[#072d3b]">Appointment</h3><p className="mt-2">{booking.confirmed_start_at ? new Date(booking.confirmed_start_at).toLocaleString("en-IE") : `Preferred: ${booking.preferred_date} · ${booking.preferred_time}`}</p><h3 className="mt-4 font-semibold text-[#072d3b]">Service address</h3><p className="mt-2">{booking.address_line_1}{booking.address_line_2 ? `, ${booking.address_line_2}` : ""}<br />{booking.city}, {booking.county} {booking.eircode}</p></div>{canCancel ? <CancelBookingButton orderId={booking.id} /> : null}</aside></div></AccountShell>
}
